services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: policy_match
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s

  tika:
    image: apache/tika:latest
    ports:
      - 9998:9998
    volumes:
      - tika_data:/var/lib/tika
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/9998'"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s

volumes:
  postgres_data:
  tika_data: